### ISSUE TITLE
Request: Radio stations

### ISSUE THREAD

**Issue by buzzbo** [96AA48/gmplayer#18]
Would it be possible to download and play songs from a station? Would be great. Thanks for everything!

**Comment by 96AA48** [comment]
As far as I know the upstream project called [playmusic](https://github.com/jamon/playmusic) does have stations on it's roadmap. However the developer (jamon) has announced that he hasn't had time recently and needs other maintainers or pull requests in order to make those features a thing.

Feel free to add that functionality to the [playmusic](https://github.com/jamon/playmusic) project with a Pull request, or let me know when that functionality has been added so I can add it to gmplayer!

Thank you for your contribution!

Happy coding!
