### ISSUE TITLE
ERROR: Error: Unable to create oauth tokenError: 403 error from server

### ISSUE THREAD

**Issue by slievr** [96AA48/gmplayer#19]
Getting this error when trying to run any instruction. Probably due to 2 factor authentication.

**Comment by egladman** [comment]
One way to circumvent this is to [generate an app password](https://myaccount.google.com/apppasswords). You'll then need to delete the cached password: `rm ~/.gmplayerrc`

**Comment by uwe-schwarz** [comment]
This did work till a few weeks ago (haven't used it in a while), but today it fails even with an app password.

**Comment by nbrandoni** [comment]
I can't generate an app password. When I follow the link Google ask my password and then this message appear: La opción de configuración que buscas no está disponible para tu cuenta.
"The setting you are looking for is not available for your account" (Google Translate).
Any suggestion?

**Comment by nbrandoni** [comment]
I try to debug the Error and i see this:
Invoke this URL https://android.clients.google.com/auth and response BadAuthentication
The final message error is: ERROR: Error: Unable to create oauth tokenError: 403 error from server

**Comment by 96AA48** [comment]
Hey everyone.

The code from `gmplayer` doesn't actually do that request, `playmusic` does, `gmplayer` just interfaces with that library. I haven't had the time to look into the issue for the `playmusic` repo, but it looks like an extra authentication effort by Google.

I think this issue is probably better of being discussed in the underlying code from @jamon 's repo [playmusic](https://github.com/jamon/playmusic/issues/27) issue 27.

**Comment by iKethavel** [comment]
hello everyone! Do you have an idea how to authorize using this plugin?

**Comment by buzzbo** [comment]
I am getting this error and I turned on 2-step authorization, generated an app password, deleted .gmplayerrc, invoked gmp, entered email address and app password (both with and without spaces), and I still get `ERROR: Error: Unable to create oauth tokenError: 403 error from server`. I checked that playmusic thread and and it's all quite confusing to me.
